version: "3.9"

services:
  api-trade-execution:
    build: .
    container_name: api-trade-execution
    ports:
      - "8002:8002"
    environment:
      APP_NAME: api-trade-execution
      LOG_LEVEL: INFO
      MONGODB_URI: mongodb://mongo-trade-execution:27017
      MONGODB_DB_NAME: trade_execution_db
      BINANCE_API_KEY: ${BINANCE_API_KEY}
      BINANCE_API_SECRET: ${BINANCE_API_SECRET}
      BINANCE_TESTNET: ${BINANCE_TESTNET:-false}
      BINANCE_TLD: ${BINANCE_TLD:-com}
    depends_on:
      - mongo-trade-execution

  mongo-trade-execution:
    image: mongo:7
    container_name: mongo-trade-execution
    ports:
      - "27029:27017"